name: CI

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Get Env
        uses: actions/github-script@v4
        with:
          script: |
            const tag = process.env.GITHUB_REF.split('/').slice(-1)[0]
            const createChangelog = require('./scripts/changelog.js')
            const content = await createChangelog('https://github.com/'+process.env.GITHUB_REPOSITORY)
            core.exportVariable('CHANGELOG', content)
            core.exportVariable('VERSION', tag)
      - name: Build
        run: |
          rm -rf ./packages/sharelist-webdav
          yarn install
          yarn build-web
          mkdir -p ./packages/sharelist/theme/default
          mkdir -p ./packages/sharelist/plugins
          cp -r ./packages/sharelist-web/dist/* ./packages/sharelist/theme/default
          cp -r ./packages/sharelist-plugin/lib/* ./packages/sharelist/plugins
          yarn build-server
      - name: Release
        run: |
          cd ./packages/sharelist/build
          tar --transform='flags=r;s|sharelist-win-x64.exe|sharelist.exe|' -zcvf sharelist_windows_amd64.tar.gz sharelist-win-x64.exe
          tar --transform='flags=r;s|sharelist-macos-x64|sharelist|' -zcvf sharelist_macos_amd64.tar.gz sharelist-macos-x64
          tar --transform='flags=r;s|sharelist-linux-x64|sharelist|' -zcvf sharelist_linux_amd64.tar.gz sharelist-linux-x64
          tar --transform='flags=r;s|sharelist-linux-arm64|sharelist|' -zcvf sharelist_linux_arm64.tar.gz sharelist-linux-arm64
          tar --transform='flags=r;s|sharelist-linuxstatic-armv7|sharelist|' -zcvf sharelist_linux_armv7.tar.gz sharelist-linuxstatic-armv7
          gh release create ${{ env.VERSION }} -n "${{ env.NOTE }}" -t "${{ env.VERSION }}" ${{ env.FILES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
          NOTE: ${{ env.CHANGELOG }}
          TITLE: ${{ env.VERSION }}
          FILES: ./*.gz